export enum EApiPathName {
  PRODUCTS = `api/v1/products`,
  CATEGORIES = `api/v1/categories`,
  USERS = `api/v1/users`,
  AUTH = `api/v1/auth`,
  CART = `api/v1/cart`,
  CART_ITEMS = `api/v1/cart-items`,
  MOCK_DATA = `api/v1/mock-data`,
  ADDRESSES = `api/v1/addresses`,
  ORDERS = `api/v1/orders`,
  ORDER_ITEMS = `api/v1/order-items`,
  ORDER_STATUS_LOGS = `api/v1/order-status-logs`,
  PAYMENT_TRANSACTION = `api/v1/payment-transaction`,
  DISCOUNT = `api/v1/discount`,
  BRANDS = `api/v1/brands`,
  CONTACTS = `api/v1/contacts`,
  PAYMENTS = `api/v1/payments`,
  ATTRIBUTES = `api/v1/attributes`,
}
