export enum ETableName {
  PRODUCT = 'products',
  CATEGORY = 'categories',
  ATTIRBUTE = 'attributes',
  USER = 'users',
  CART = 'carts',
  CART_ITEM = 'cart_items',
  ADDRESS = 'addresses',
  ORDER = 'orders',
  ORDER_ITEM = 'order_items',
  ORDER_STATUS_LOG = 'order_status_logs',
  PAYMENT = 'payments',
  DISCOUNT = 'discounts',
  BRAND = 'brands',
  CONTACT = 'contacts',
}
